version: '3'
services:
  go:
    build: .
    ports:
      - "3001:3001"
    tty: true
    volumes:
      - .:/go/src/workspace
      - app-data:/app/data
    working_dir: /go/src/workspace

volumes:
  app-data:
